export const ADD_TODO = 'ADD_TODO'

export const GET_TODOS = 'GET_TODOS'
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS'
export const GET_TODOS_FAIL = 'GET_TODOS_FAIL'

export const POST_TODO = 'POST_TODO'
export const POST_TODO_SUCCESS = 'POST_TODO_SUCCESS'
export const POST_TODO_FAIL = 'POST_TODO_FAIL'

export const GET_DUMMY_DATA = 'GET_DUMMY_DATA'
export const GET_DUMMY_DATA_SUCCESS = 'GET_DUMMY_DATA_SUCCESS'
export const GET_DUMMY_DATA_FAIL = 'GET_DUMMY_DATA_FAIL'
